FROM gradle:latest AS builder
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build

FROM openjdk:17

ARG SERVER_PORT
COPY --from=builder /home/gradle/src/build/libs/carsharing-1.0.0.jar /app/main.jar
EXPOSE $SERVER_PORT
ENTRYPOINT ["java", "-jar", "/app/main.jar"]