FROM php:7.4-apache

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

WORKDIR /var/www/html

COPY ./index.php /var/www/html
COPY ./create.php /var/www/html
COPY ./delete.php /var/www/html
COPY ./update.php /var/www/html
COPY ./style.css /var/www/html

EXPOSE 80