version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: appDB
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - application
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - 8081:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/appDB?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - application

volumes:
  db:

networks:
  application: