version: '3'
services:
  gateway:
    build: 
        context: .
        dockerfile: ./dockerfile.gateaway
    ports:
      - 8081:8081
    depends_on:
      - message-service 
      - user-service
    
  message-service:
    build: 
        context: .
        dockerfile: ./dockerfile.message
    ports:
      - 50051:50051

  user-service:
    build: 
        context: .
        dockerfile: ./dockerfile.user
    ports:
      - 50052:50052

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gateway
