version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "exec_async"
      POSTGRES_USER: "shiz"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./queue_realization_4.sql:/docker-entrypoint-initdb.d/queue_realization.sql
    ports:
      - "5435:5432"