version: '3.8'
services:
  app-prac6:
      build:
        context: .
        dockerfile: Dockerfile2
      container_name: app-prac6
      ports:
        - "8080:8080"
      depends_on:
        - db-prac6
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db-prac6:5432/market
        SPRING_DATASOURCE_USERNAME: market
        SPRING_DATASOURCE_PASSWORD: market
  web:
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db-prac6:
    image: postgres
    container_name: db-prac6
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: market
      POSTGRES_PASSWORD: market
  db:
    image: postgres
    environment:
      POSTGRES_DB: prac12py
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
  media_volume:
  db-data:
