version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: GetContact
    ports:
      - "5433:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis
    ports:
      - 6379:6379

  authservice:
    build:
      context: ./auth
      dockerfile: AuthDockerfile
    ports:
      - "8082:8081"
    depends_on:
      - redis
    links:
      - "redis"

  app:
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/carsharing
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password