version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "sidorov_tot_prakt"
      POSTGRES_USER: "shiz"
      POSTGRES_PASSWORD: "1"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"