version: '3'

services:
  db:
    build: .
    environment:
      POSTGRES_DB: "sidorov_tot_prakt"
      POSTGRES_USER: "shiz"
      POSTGRES_PASSWORD: "1"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      #- ./functions1.sql:/docker-entrypoint-initdb.d/functions.sql
    ports:
      - "5435:5432"