version: '3'
services:
  php-apache:
    image: php:7.4-apache
    ports:
      - "8081:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge