CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT, DELETE ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;

CREATE TABLE IF NOT EXISTS note (
  id INT NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(40) NOT NULL,
  phone VARCHAR(13) NOT NULL,
  description VARCHAR(255) NOT NULL,
  PRIMARY KEY (ID)
);

